<?php
$addressHelper = $this->helper(Medbuy\Customer\Helper\Address::class);
$isLoggedIn = $addressHelper->isLoggedIn();

$countries = $block->getCountryHtmlSelect();
$search = array('id="country" class=""', '<option value="" > </option>');
$replace = array('id="country" class="country form-control"', '<option value="" disabled="" selected="">' . __('Countries') . ' *</option>"');
$countries = str_replace($search, $replace, $countries);

$customAttributeHelper = $this->helper(Medbuy\CustomerAttribute\Helper\Customerattribute::class);
$customAttributeCollection = $customAttributeHelper->getUserDefinedAttribures();

$minPasLength = $block->getMinimumPasswordLength();

if ($customAttributeCollection->count() > 0) {
    foreach ($customAttributeCollection as $attribute) {
        $frontEndLabel = $attribute->getStoreLabel($customAttributeHelper->getStoreId());
        $fieldRequiredClass = ($attribute->getIsRequired()) ? 'data-validate="{required:true}"' : '';
        if ($block->getFormData()->getData($attribute->getAttributeCode())) {
            $fieldValue = $block->getFormData()->getData($attribute->getAttributeCode());
        } else {
            $fieldValue = $attribute->getDefaultValue();
        }
        if ($attribute->getIsRequired()) {
            $required = 'required';
        } else {
            $required = '';
        }
        if ($attribute->getAttributeCode() == 'kind_of_activity_buyer' || $attribute->getAttributeCode() == 'type_company') {
            $contentOptions = '';
            $options = $customAttributeHelper->getAttributeOptions($attribute->getAttributeCode());
            foreach ($options as $option) {
                if ($option['value'] == $fieldValue) {
                    $selected = 'selected';
                } else {
                    $selected = '';
                }
                $contentOptions .= '<option value="' . $option['value'] . '" ' . $selected . '>' . $option['label'] . '</option>';
            }
            if ($attribute->getAttributeCode() == 'kind_of_activity_buyer') {
                $kindActivityContent = '<select class="form-control ' . $required . '" id="' . $attribute->getAttributeCode() . '" name="' . $attribute->getAttributeCode() . '" title="' . __($frontEndLabel) . '">' .
                        $contentOptions .
                        '</select>';
            } elseif ($attribute->getAttributeCode() == 'type_company') {
                $typeCompanyHtml = '<select id="' . $attribute->getAttributeCode() . '" name="' . $attribute->getAttributeCode() . '" class="form-control ' . $required . '">' .
                        $contentOptions .
                        '</select>';
            }
        } elseif ($attribute->getAttributeCode() == 'login') {
            $loginHtml = '<input type="text" name="login" class="form-control ' . $required . '" placeholder="' . __($frontEndLabel) . ' *">';
        } elseif ($attribute->getAttributeCode() == 'post') {
            $postHtml = '<input type="text" name="post" onblur = "validateFiled(this)" class="form-control ' . $required . '" placeholder="' . __($frontEndLabel) . ' *">';
        } elseif ($attribute->getAttributeCode() == 'company_website') {
            $companyWebsiteHtml = '<input type="text" name="company_website" class="form-control ' . $required . '" placeholder="' . __($frontEndLabel) . '">';
        } elseif ($attribute->getAttributeCode() == 'mobile_phone') {
            $mobilePhoneHtml = '<label for="' . $attribute->getAttributeCode() . '">' . __($frontEndLabel) . '*</label>
                                    <input type="text" id="' . $attribute->getAttributeCode() . '" name="' . $attribute->getAttributeCode() . '" class="form-control ' . $required . '" placeholder="+380 __ ___-__-__">';
        }
    }
}
?>

<div class="customer register" style="background-image: url('<?php echo $this->getViewFileUrl('images/customer/account-register-content-bg.png') ?>')">
    <div class="tabs">
        <!--<div class="tabs items" data-mage-init='{"tabs":{"openedState":"active"}}'>-->
        <div class="tabs items">
            <div class="tabs item title" aria-labeledby="tab-label-buyer-title" data-role="collapsible" id="tab-label-buyer">
                <a class="switch" tabindex="-1" data-toggle="switch" href="#buyer" id="tab-label-buyer-title">
                    <?= /* @escapeNotVerified */ __("Buyer") ?>
                </a>
            </div>
            <div class="tabs item title" aria-labeledby="tab-label-seller-title" data-role="collapsible" id="tab-label-seller">
                <a class="switch" tabindex="-1" data-toggle="switch" href="#seller" id="tab-label-seller-title">
                    <?= /* @escapeNotVerified */ __("Seller") ?>
                </a>
            </div>

            <div class="tabs item content" id="buyer" data-role="content">
                <div class="create account wrapper buyer">

                    <?= $block->getChildHtml('form_fields_before') ?>
                    <?php /* Extensions placeholder */ ?>
                    <?= $block->getChildHtml('customer.form.register.extra') ?>

                    <div class="create account col-title">
                        <div class="create account title-wrapper">
                            <div class="create account title"><?php echo __("Create New Customer Account") ?></div>
                        </div>
                    </div>

                    <div class="create account col-form">
                        <form class="form create account form-create-account"
                              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                              method="post"
                              id="form-validate"
                              enctype="multipart/form-data"
                              autocomplete="off">

                            <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
                            <input type="hidden" name="create_address" value="1" />
                            <input type="hidden" name="default_billing" value="1">
                            <input type="hidden" name="default_shipping" value="1">
                            <input type="hidden" name="acc_type" value="1">
                            <input type="hidden" name="check_valid" value="0">

                            <fieldset class="fieldset create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                                <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend>
                                <div class="sub-title"><?php echo __("Customer Account Authorization Data") ?></div>

                                <div class="field required">
                                    <div class="control">
                                        <input type="email" name="email" id="email_address"
                                               autocomplete="email"
                                               onblur="validateEmail(this)"
                                               value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>"
                                               title="<?= $block->escapeHtmlAttr(__('E-mail')) ?> *"
                                               class="input-text"
                                               placeholder="<?= $block->escapeHtmlAttr(__('E-mail')) ?> *"
                                               data-validate="{required:true, 'validate-email':true}">
                                    </div>
                                </div>

                                <div class="field password required">
                                    <div class="control">
                                        <input type="password" name="password" id="password"
                                               title="<?= $block->escapeHtmlAttr(__('Password')) ?> *"
                                               class="input-text"
                                               onblur="validatePassword(this)"
                                               placeholder="<?= $block->escapeHtmlAttr(__('Password')) ?> *"
                                               data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                               data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                               data-validate="{required:true, 'validate-customer-password':true}"
                                               autocomplete="off">

                                        <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                            <div id="password-strength-meter" class="password-strength-meter">
                                                <?= $block->escapeHtml(__('Password Strength')) ?>:
                                                <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                                    <?= $block->escapeHtml(__('No Password')) ?>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="field confirmation required">
                                    <div class="control">
                                        <input
                                            type="password"
                                            name="password_confirmation"
                                            title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?> *"
                                            id="password-confirmation"
                                            onblur="validateConfirmPasswordBuyer()"
                                            class="input-text"
                                            data-validate="{required:true, equalTo:'#password'}"
                                            autocomplete="off"
                                            placeholder="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?> *"
                                            >
                                    </div>
                                </div>

                                <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

                                <div class="form-group form-country">
                                    <?= $countries ?>
                                </div>
                                <div class="form-group">
                                    <?php echo $kindActivityContent; ?>
                                </div>
                                <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
                                <?php if ($_company->isEnabled()): ?>
                                    <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                                <?php endif ?>

                                <?php echo $block->getChildHtml('form_additional_info') ?>
                            </fieldset>

                            <fieldset class="fieldset create info">
                                <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
                                <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
                                <?php if ($block->isNewsletterEnabled()): ?>
                                    <div class="field choice newsletter">
                                        <input type="checkbox" name="is_subscribed" title="<?= $block->escapeHtmlAttr(__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if ($block->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox">
                                        <label for="is_subscribed" class="label"><span><?= $block->escapeHtml(__('Sign Up for Newsletter')) ?></span></label>
                                    </div>
                                    <?php /* Extensions placeholder */ ?>
                                    <?= $block->getChildHtml('customer.form.register.newsletter') ?>
                                <?php endif ?>

                                <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
                                <?php if ($_dob->isEnabled() && $isLoggedIn): ?>
                                    <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
                                <?php endif ?>

                                <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
                                <?php if ($_taxvat->isEnabled()): ?>
                                    <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
                                <?php endif ?>

                                <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
                                <?php if ($_gender->isEnabled() && $isLoggedIn): ?>
                                    <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
                                <?php endif ?>
                            </fieldset>

                            <?php if ($block->getShowAddressFields()): ?>
                                <fieldset class="fieldset address">
                                    <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend>
                                    <input type="hidden" name="create_address" value="1" />

                                    <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
                                    <?php if ($_company->isEnabled()): ?>
                                        <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                                    <?php endif ?>

                                    <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
                                    <?php if ($_telephone->isEnabled()): ?>
                                        <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
                                    <?php endif ?>

                                    <?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
                                    <?php if ($_fax->isEnabled()): ?>
                                        <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
                                    <?php endif ?>

                                    <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

                                    <div class="field street required">
                                        <label for="street_1" class="label"><span><?= $block->escapeHtml(__('Street Address')) ?></span></label>
                                        <div class="control">
                                            <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address')) ?>" id="street_1" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                            <div class="nested">
                                                <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                                                <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                                                    <div class="field additional">
                                                        <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                                            <span><?= $block->escapeHtml(__('Address')) ?></span>
                                                        </label>
                                                        <div class="control">
                                                            <input type="text" name="street[]" value="<?= $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" title="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="input-text <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                                        </div>
                                                    </div>
                                                <?php endfor; ?>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="field required">
                                        <label for="city" class="label"><span><?= $block->escapeHtml(__('City')) ?></span></label>
                                        <div class="control">
                                            <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" title="<?= $block->escapeHtmlAttr(__('City')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>" id="city">
                                        </div>
                                    </div>

                                    <div class="field region required">
                                        <label for="region_id" class="label"><span><?= $block->escapeHtml(__('State/Province')) ?></span></label>
                                        <div class="control">
                                            <select id="region_id" name="region_id" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="validate-select" style="display:none;">
                                                <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                            </select>
                                            <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>" title="<?= $block->escapeHtmlAttr(__('State/Province')) ?>" class="input-text <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>" style="display:none;">
                                        </div>
                                    </div>

                                    <div class="field zip required">
                                        <label for="zip" class="label"><span><?= $block->escapeHtml(__('Zip/Postal Code')) ?></span></label>
                                        <div class="control">
                                            <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" title="<?= $block->escapeHtmlAttr(__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                                        </div>
                                    </div>

                                    <div class="field country required">
                                        <label for="country" class="label"><span><?= $block->escapeHtml(__('Country')) ?></span></label>
                                        <div class="control">
                                            <?= $block->getCountryHtmlSelect() ?>
                                        </div>
                                    </div>
                                    <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes'); ?>
                                    <?php if ($addressAttributes): ?>
                                        <?php $addressAttributes->setEntityType('customer_address'); ?>
                                        <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]'); ?>
                                        <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address'); ?>
                                        <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
                                    <?php endif; ?>
                                    <input type="hidden" name="default_billing" value="1">
                                    <input type="hidden" name="default_shipping" value="1">
                                </fieldset>

                            <?php endif; ?>

                            <div class="actions-toolbar">
                                <div class="primary">
                                    <button id="buyer-form-submit" class="action submit primary btn-block" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>">
                                        <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
                                    </button>
                                </div>
                            </div>
                        </form>
                        <script>
                            require(['jquery','mage/mage'], 
                                function ($) {
                                    var dataForm = $('#form-validate');
                                    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
                                    dataForm.mage('validation', {
                                        <?php if ($_dob->isEnabled()): ?>
                                            errorPlacement: function (error, element) {
                                                if (element.prop('id').search('full') !== - 1) {
                                                    var dobElement = $(element).parents('.customer-dob'),
                                                            errorClass = error.prop('class');
                                                    error.insertAfter(element.parent());
                                                    dobElement.find('.validate-custom')
                                                            .addClass(errorClass)
                                                            .after('<div class="' + errorClass + '"></div>');
                                                } else {
                                                    error.insertAfter(element);
                                                }
                                            },
                                            ignore: ':hidden:not(' + ignore + ')'
                                        <?php else: ?>
                                            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                                        <?php endif ?>
                                    }).find('input:text').attr('autocomplete', 'off');
                                });
                        </script>

                        <?php if ($block->getShowAddressFields()): ?>
                            <script type="text/x-magento-init">
                                {
                                    "#country": {
                                        "regionUpdater": {
                                            "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                                            "regionListId": "#region_id",
                                            "regionInputId": "#region",
                                            "postcodeId": "#zip",
                                            "form": "#form-validate",
                                            "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                                            "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                                            "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                                        }
                                    }
                                }
                            </script>
                        <?php endif; ?>

                        <script type="text/x-magento-init">
                            {
                                ".field.password": {
                                    "passwordStrengthIndicator": {
                                        "formSelector": "form.form-create-account"
                                    }
                                }
                            }
                        </script>
                    </div>
                </div>
            </div>

            <!--Registration seller form-->
            <div class="tabs item content" id="seller" data-role="content">
                <div class="create account wrapper seller">

                    <div class="create account col-title">
                        <div class="create account title-wrapper">
                            <div class="create account title"><?php echo __("Create New Seller Account") ?></div>
                        </div>
                    </div>
                    <div class="create account col-form" data-view-step="primary" data-role="step-wrapper">
                        <form class="create account form form-create-seller-account seller-form"
                              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"                              
                              method="post"
                              id="seller-form-validate"
                              enctype="multipart/form-data"
                              autocomplete="off">
                                  <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
                            <input type="hidden" name="create_address" value="1" />
                            <input type="hidden" name="default_billing" value="1">
                            <input type="hidden" name="default_shipping" value="1">
                            <input type="hidden" name="acc_type" value="5">
                            <input type="hidden" name="check_valid" value="0">

                            <div id="step1" class="create account" data-role="step" data-step="primary">
                                <fieldset class="fieldset create account seller" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                                    <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend>
                                    <div class="sub-title"><?php echo __("Customer Account Authorization Data") ?></div>

                                    <div class="field required">
                                        <div class="control">
                                            <input type="email" name="email" id="email_address_seller"
                                                   autocomplete="email"
                                                   onblur="validateEmail(this)"
                                                   value=""
                                                   title="<?= $block->escapeHtmlAttr(__('E-mail')) ?> *"
                                                   class="input-text"
                                                   placeholder="<?= $block->escapeHtmlAttr(__('E-mail')) ?> *"
                                                   data-validate="{required:true, 'validate-email':true}" required>
                                        </div>
                                    </div>

                                    <div class="field seller-password required">
                                        <div class="control">
                                            <input type="password" name="password" id="password_seller"
                                                   title="<?= $block->escapeHtmlAttr(__('Password')) ?> *"
                                                   class="input-text"
                                                   onblur="validatePassword(this)"
                                                   placeholder="<?= $block->escapeHtmlAttr(__('Password')) ?> *"
                                                   data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                                   data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                                   data-validate="{required:true, 'validate-customer-password':true}"
                                                   autocomplete="off" required>

                                            <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                                                <div id="password-strength-meter" class="password-strength-meter">
                                                    <?= $block->escapeHtml(__('Password Strength')) ?>:
                                                    <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                                        <?= $block->escapeHtml(__('No Password')) ?>
                                                    </span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="field confirmation required">
                                        <div class="control">
                                            <input
                                                type="password"
                                                name="password_confirmation"
                                                title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?> *"
                                                id="password-confirmation_seller"
                                                class="input-text"
                                                data-validate="{required:true, equalTo:'#password'}"
                                                autocomplete="off"
                                                placeholder="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?> *" required>
                                        </div>
                                    </div>
                                </fieldset>

                                <div class="actions-toolbar">
                                    <div class="primary">
                                        <button type="button" 
                                                class="action submit primary btn-block"
                                                id="step-rotation"
                                                data-role="btn-step-rotation" 
                                                data-target="secondary" title="<?= $block->escapeHtmlAttr(__('Next')) ?>">
                                            
                                                    <span><?= $block->escapeHtml(__('Next')) ?></span>
                                        </button>
                                    </div>
                                </div>
                            </div>

                            <div id="step2" class="create account" data-role="step" data-step="secondary">
                                <fieldset class="fieldset create account seller" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
                                    <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend>
                                    <div class="sub-title"><?php echo __("Customer Account Authorization Data") ?></div>

                                    <div class="row">
                                        <?php echo $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                                    </div>

                                    <div class="field required delimiter">
                                        <div class="control">
                                            <?php echo $postHtml ?>
                                        </div>
                                    </div>

                                    <div class="field required">
                                        <div class="control">
                                            <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
                                            <?php if ($_company->isEnabled()): ?>
                                                <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
                                            <?php endif ?>
                                        </div>
                                    </div>

                                    <div class="row delimiter">
                                        <div class="col-12">
                                            <div class="field required">
                                                <div class="control">
                                                    <?php echo $typeCompanyHtml ?>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-7">
                                            <div class="field required">
                                                <div class="control">
                                                    <input type="text" name="company_website" id="company_website" class="input-text" placeholder="<?php echo __("Company Web Site") ?>"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-19">
                                            <label><?php echo __("Address") ?> *</label>
                                        </div>

                                        <div class="col">
                                            <div class="field required">
                                                <div class="control">
                                                    <?php echo $countries ?>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col">
                                            <div class="field required">
                                                <div class="control">
                                                    <input type="text" 
                                                           name="city" 
                                                           onblur = "validateFiled(this)"
                                                           id="city" 
                                                           class="input-text" 
                                                           placeholder="<?php echo __("City") ?>"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col">
                                            <div class="field">
                                                <div class="control">
                                                    <input type="text" 
                                                           name="street" 
                                                           onblur = "validateFiled(this)"
                                                           id="street" 
                                                           class="input-text" 
                                                           placeholder="<?php echo __("Street") ?>"/>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-7">
                                            <div class="field">
                                                <div class="control">
                                                    <input type="text" 
                                                           name="building" 
                                                           onblur = "validateFiled(this)"
                                                           id="building" 
                                                           class="input-text" 
                                                           placeholder="<?php echo __("Building") ?>"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-7">
                                            <div class="field required delimiter">
                                                <div class="control">
                                                    <input type="text" 
                                                           name="office" 
                                                           id="office" 
                                                           onblur = "validateFiled(this)"
                                                           class="input-text" 
                                                           placeholder="<?php echo __("Office") ?>"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-10">
                                            <div class="field required">
                                                <div class="control">
                                                    <label for="phone"><?php echo __("Work Phone") ?> *</label>
                                                    <input id="phone" 
                                                           name="phone" 
                                                           type="text" 
                                                           onblur = "validatePhone(this)"
                                                           class="input-text" 
                                                           placeholder="+38 (0__) ___–__–__"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-10">
                                            <div class="field required">
                                                <div class="control">
                                                    <label for="mobile_phone"><?php echo __("Work Mobile") ?> *</label>
                                                    <input id="mobile_phone" 
                                                           name="mobile_phone" 
                                                           type="text" 
                                                           onblur = "validatePhone(this)"
                                                           class="input-text" 
                                                           placeholder="+38 (0__) ___–__–__"/>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>

                                <div class="actions-toolbar">
                                    <div class="row">
                                        <div class="col">
                                            <button class="btn btn-secondary btn-block" 
                                                    id="back-step-rotation"
                                                    data-role="btn-step-rotation" 
                                                    data-target="primary" 
                                                    type="button">
                                                
                                                        <i class="fas fa-arrow-left"></i> <?php echo __("Go Back") ?>
                                                
                                            </button>
                                        </div>
                                        <div class="col">
                                            <button class="btn btn-primary btn-block" data-role="btn-register">
                                                <?php echo __("Register") ?>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                        <script>
                            require(['jquery','mage/mage'], 
                                function ($) {
                                    var dataForm = $('#seller-form-validate');
                                    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;
                                    dataForm.mage('validation', {
                                        <?php if ($_dob->isEnabled()): ?>
                                            errorPlacement: function (error, element) {
                                                if (element.prop('id').search('full') !== - 1) {
                                                    var dobElement = $(element).parents('.customer-dob'),
                                                            errorClass = error.prop('class');
                                                    error.insertAfter(element.parent());
                                                    dobElement.find('.validate-custom')
                                                            .addClass(errorClass)
                                                            .after('<div class="' + errorClass + '"></div>');
                                                } else {
                                                    error.insertAfter(element);
                                                }
                                            },
                                            ignore: ':hidden:not(' + ignore + ')'
                                        <?php else: ?>
                                            ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
                                        <?php endif ?>
                                    }).find('input:text').attr('autocomplete', 'off');
                                });
                        </script>

                        <?php if ($block->getShowAddressFields()): ?>
                            <script type="text/x-magento-init">
                                {
                                    "#country": {
                                        "regionUpdater": {
                                            "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                                            "regionListId": "#region_id",
                                            "regionInputId": "#region",
                                            "postcodeId": "#zip",
                                            "form": "#seller-form-validate",
                                            "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                                            "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                                            "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
                                        }
                                    }
                                }
                            </script>
                        <?php endif; ?>
                            
                        <script type="text/x-magento-init">
                            {
                                ".field.seller-password": {
                                    "passwordStrengthIndicator": {
                                        "formSelector": "form.form-create-seller-account"
                                    }
                                }
                            }
                        </script>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<div id="registerPopupSuccess" class="modal-alert modal-inner-content">
    <p class="modal-alert-message"><?php echo __("Your details on the verification from the administration. Within 24 hours you will receive a notification of successful registration by e-mail") ?></p>
</div>

<script>
    require(['jquery', 'Magento_Ui/js/modal/modal'],
            function ($, modal) {

                $(document).ready(function() {
                      $('form').keydown(function(event){
                        if(event.keyCode == 13) {
                          event.preventDefault();
                          return false;
                      }
                   });
                });                
                var options = {
                    modalClass:  '_alert',
                        innerScroll: true,
                        focus:       '',
                        title:       $.mage.__('Register'),
                        buttons: [
                            {
                                text:  $.mage.__('Ok'),
                                    class: 'btn btn-primary',
                                    click: function () {
                                        this.closeModal();
                                    }
                            }
                        ]
                    };
                
                var popup = modal(options, $('#registerPopupSuccess'));
                
                $('#buyer-form-submit').on('click', buyerFormSubmit);
                
                function buyerFormSubmit(){
                    var result = true;
                    $('#buyer form input[type!=hidden]').each(function(){
                        if($(this).val() == ''){
                            if($(this).attr('type') == 'email'){
                                $(this).attr('placeholder','Введите свой emal *');
                            } else if ($(this).attr('type') == 'password'){
//                                $(this).attr('type', 'text');
                                $(this).attr('placeholder','Введите свой пароль *');    
                            } else if($(this).attr('name') == 'firstname'){
                                $(this).attr('placeholder','Введите имя *');
                            } else if ($(this).attr('name') == 'lastname'){
                                $(this).attr('placeholder','Введите фаимлию *');
                            }
                            
                            if($(this).attr('name') != 'company'){
                                $(this).css({                                
                                    'border': '1px solid red'
                                });
                                $(this).addClass('empty');
                                result = false;
                            }
                        }
                    });
                    var confPs = checkConfirmPasswordBuyer();
                    if(result && confPs){                        
                        $('input[name=check_valid]').val('1');
                        $('form.seller-form').submit();
                    } else {
                        if(confPs){
//                            alert('Заполните обязательные поля');   
                        }
                        
                        return result;
                    }
                }
                
                function checkConfirmPasswordBuyer(){
                    var result = true;
                    if($('#password').val() != $('#password-confirmation').val()){
                        $('#password-confirmation').val('');
                        $('#password-confirmation').attr('placeholder', 'Введенные пароли не совпадают, обновите страницу и попробуйте еще раз.');
                        $('#password-confirmation').css({
                            'border': '1px solid red'
                        });
                        $('#password').css({
                            'border': '1px solid red'
                        });
                        
                        
                        result = false;
                    }
                    return result;
                }
                
                $('#back-step-rotation').on('click', function (e) {
                    e.preventDefault();
                    var $stepWrap = $('[data-role=step-wrapper]');
                    $stepWrap.attr('data-view-step', $(this).attr("data-target"));
                });
                $('[data-role=btn-register]').on('click', function (e) {
                    var resCeck = checkInputStep2();
                    if(resCeck){
                        $('#registerPopupSuccess').modal('openModal');
                    } else {                        
                        e.preventDefault();
                    }
                });
                function checkInputStep2(){
                    var result = true;
                    $('#step2 input[type=text]').each(function(){
                        if($(this).val() == ''){
                            if($(this).attr('name') == 'firstname'){
                                $(this).attr('placeholder','Введите имя *');
                            } else if ($(this).attr('name') == 'lastname'){
                                $(this).attr('placeholder','Введите фаимлию *');
                            } else if ($(this).attr('name') == 'post'){
                                $(this).attr('placeholder','Введите должность *');
                            } else if ($(this).attr('name') == 'city'){
                                $(this).attr('placeholder','Введите город *');
                            } else if ($(this).attr('name') == 'street'){
                                $(this).attr('placeholder','Введите улицу *');
                            } else if ($(this).attr('name') == 'building'){
                                $(this).attr('placeholder','Введите номер дома *');
                            } else if ($(this).attr('name') == 'office'){
                                $(this).attr('placeholder','Введите номер офиса *');
                            } else if ($(this).attr('name') == 'phone'){
                                $(this).attr('placeholder','Введите номер рабочего телефона *');
                            } else if ($(this).attr('name') == 'mobile_phone'){
                                $(this).attr('placeholder','Введите номер мобильного телефона *');
                            }
                            
                            if($(this).attr('name') != 'company_website' && $(this).attr('name') != 'company'){
                                $(this).css({                                
                                    'border': '1px solid red'
                                });
                                $(this).addClass('empty');
                                result = false;
                            }
                        } else {
                            $(this).css({                                
                                'border': '1px solid #ced4da'
                            });                            
                        }
                    });
                    
                    
                    if(result){                        
                        $('input[name=check_valid]').val('1');
                        $('form.seller-form').submit();
                    } else {
//                        alert('Заполните обязательные поля');   
                        return result;
                    }
                }
                
// Seller Form step rotation
                $('#step-rotation').on('click', function (e) { 
                    var resCeck = checkInputStep1();
                    if(resCeck){
                        var confPs = checkConfirmPassword();
                        if(confPs){
                            e.preventDefault();
                            var $stepWrap = $('[data-role=step-wrapper]');
                            $stepWrap.attr('data-view-step', $(this).attr("data-target"));
                        }
                    }
                });
                function checkInputStep1(){
                    var result = true;
                    $('#step1 input').each(function(){
                        if($(this).val() == ''){
                            if($(this).attr('type') == 'email'){
                                $(this).attr('placeholder','Введите свой emal *');
                            } else if ($(this).attr('type') == 'password'){
                                $(this).attr('placeholder','Введите свой пароль *');    
                            }
                            $(this).css({
                                'border': '1px solid red'
                            });
                            $(this).addClass('empty');
                            result = false;
                        }
                    });
                    if($('div').is('#password_seller-error') && document.getElementById('password_seller-error').style.display != 'none'){                        
                        result = false;
                    }
                    
                    return result;
                }
                
                function checkConfirmPassword(){
                    var result = true;
                    if($('#password_seller').val() != $('#password-confirmation_seller').val()){
                        $('#password-confirmation_seller').attr('placeholder', 'Введенные пароли не совпадают, обновите страницу и попробуйте еще раз.');
                        $('#password-confirmation_seller').css({
                            'border': '1px solid red'
                        });
                        $('#password_seller').css({
                            'border': '1px solid red'
                        });
                        result = false;
                    }
                    return result;
                }                
            }
    );
    
    
// validate fileds    
    function validatePassword(el){
        var minPasLength = Number('<?php echo $minPasLength ?>');
        if(el.value.length <  minPasLength){
           el.value = ''; 
        }
    }
    
    function validateConfirmPasswordBuyer(){
        var result = true, actveTabId, el;
        var pass = document.getElementById('password');
        var confPass = document.getElementById('password-confirmation');
        if(pass.value != confPass.value){
            pass.value = '';
            confPass.value = '';
            confPass.setAttribute('placeholder', 'Введенные пароли не совпадают');
            pass.style.border = '1px solid red';            
            pass.classList.add('empty');
            confPass.style.border = '1px solid red';            
            confPass.classList.add('empty');
            result = false;
        } else {
            pass.style.border = '1px solid #ced4da'; 
            confPass.style.border = '1px solid #ced4da';   
        }
    }
    function validateEmail(el){
        var result = true;
        var res = el.value.match(/.+?\@.+/g);
        if(res == null){
            result = false;
            el.value = '';
            el.setAttribute('placeholder', 'Введите корректый email адрес *');
            el.style.border = '1px solid red';            
            el.classList.add('empty');
        } else {
            el.style.border = '1px solid #ced4da';            
        }
    }
    function validatePhone(el){
        var result = true;
        var res = el.value.match(/[0-9]{7,18}/);
        if(res == null || (res != null && el.value.length >= 19)){
            result = false;
            el.value = '';            
            el.style.border = '1px solid red';            
            el.classList.add('empty');
        } else {
            el.style.border = '1px solid #ced4da';
        }
    }    
    function validateFiled(el){
        var result = true; 
        
        if(el.value == ''){
            var val = el.getAttribute('name');
            if(val == 'firstname'){                
                el.setAttribute('placeholder', 'Введите имя *');
            } else if (val == 'lastname'){
                el.setAttribute('placeholder', 'Введите фаимлию *');
            } else if (val == 'post'){
                el.setAttribute('placeholder', 'Введите должность *');
            } else if (val == 'company'){
                el.setAttribute('placeholder', 'Введите название компании *');
            } else if (val == 'city'){
                el.setAttribute('placeholder', 'Введите город *');
            } else if (val == 'street'){
                el.setAttribute('placeholder', 'Введите улицу *');
            } else if (val == 'building'){
                el.setAttribute('placeholder', 'Введите номер дома *');
            } else if (val == 'office'){
                el.setAttribute('placeholder', 'Введите номер офиса *');
            } else if (val == 'phone'){
                el.setAttribute('placeholder', 'Введите номер рабочего телефона *');
            } else if (val == 'mobile_phone'){
                el.setAttribute('placeholder', 'Введите номер мобильного телефона *');
            }

            el.style.border = '1px solid red';            
            el.classList.add('empty');

            result = false;
        } else {
            el.style.border = '1px solid #ced4da';
        }
    }
// end validate fileds   
</script>
<script>
    require(['jquery', 'tabs'],
            function ($) {
                $(".tabs.items").tabs({
                    "openedState":"active"
                });
                $(document).ready(function(){
                    setUniqueId($);
                });
                
                function setUniqueId($) {
                    var noActveTabId, actveTabId,
                            tabs = $('.items').find('.item.title'),
                            uniqueId = ['company', 'country', 'firstname', 'lastname', 'register_form'];

                    tabs.each(function () {
                        if (!$(this).hasClass('active')) {
                            noActveTabId = $(this).attr('id');
                        } else {
                            actveTabId = $(this).attr('id');
                        }
                    });

                    var idContentNoActiveTab = noActveTabId.split('-').pop();
                    var idContentActiveTab = actveTabId.split('-').pop();

                    uniqueId.forEach(function (el) {
                        if (typeof $('#' + idContentNoActiveTab).find('.' + el).attr('id') != 'undefined') {
                            $('#' + idContentNoActiveTab).find('.' + el).removeAttr('id');
                        }
                        if (typeof $('#' + idContentActiveTab).find('.' + el).attr('id') == 'undefined') {
                            if (el == 'register_form') {
                                $('#' + idContentActiveTab).find('.' + el).attr('id', 'form-validate');
                            } else {
                                $('#' + idContentActiveTab).find('.' + el).attr('id', el);
                            }
                        }
                    });
                }                
            });
</script>
